<?php

namespace Backend\modules\common\controllers;

use Backend\behavior\Log;
use yii\filters\auth\HttpBearerAuth;

/**
 * Created by PhpStorm.
 * User: tianweimin
 * Date: 2018/3/21
 * Time: 15:05
 */
class CommonController extends JwtController
{

    public function behaviors()
    {
        //用户认证, 传递头信息为bearer token
        $behaviors = parent::behaviors();
//        $behaviors['authenticator'] = [
//            'class' => HttpBearerAuth::className(),
//        ];

        $behaviors['logRequest'] = Log::class;
        return $behaviors;
    }

    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        $this->logRequest();
        return true;
    }
}