<?php

namespace Backend\modules\common\controllers;

use Api\modules\authentication\models\Jwt;
use Api\modules\authentication\services\JwtService;
use Backend\Exception\CustomException;
use Backend\helpers\Helpers;
use Backend\helpers\Lang;
use yii\helpers\ArrayHelper;

/**
 * 校验token有效性
 * User: tianweimin
 * Date: 2018/3/21
 * Time: 15:05
 */
class JwtController extends BaseController
{
    public function beforeAction($action)
    {
        $tokenString = Helpers::getHeader('Authorization');
        $jwtService = new JwtService(new Jwt(), $tokenString);
        //解析并校验token
        if (!$jwtService->parseToken()->validateToken()) {
            throw new CustomException(Lang::ERR_TOKEN_INVALID);
        }

        //设置登录账号
        \Yii::$app->user->identity = $jwtService->jwtObj->admin;

        //验证游戏权限
        $gameId = Helpers::getRequestParam('game_id');
        \Yii::$app->user->identity->validateGame($gameId, \Yii::$app->user->identity->jwt->getGameIdsByToken());

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}