<?php

namespace Backend\modules\common\controllers;

use Api\modules\authentication\models\Jwt;
use Api\modules\authentication\services\JwtService;
use Backend\Exception\CustomException;
use Backend\helpers\Helpers;
use Backend\helpers\Lang;

/**
 * 校验token有效性
 * 通过后即账号认证成功
 * User: tianweimin
 * Date: 2018/3/21
 * Time: 15:05
 */
class JwtController extends BaseController
{
    public function beforeAction($action)
    {
        $tokenString = Helpers::getHeader('Authorization');
        if (empty($tokenString)) {
            $tokenString = Helpers::getRequestParam('Authorization');
        }
        $jwtService = new JwtService(new Jwt(), $tokenString);
        //解析并校验token
        if (!$jwtService->parseToken()->validateToken()) {
            throw new CustomException(Lang::ERR_TOKEN_INVALID);
        }

        //校验sid一致性
        if(intval(Helpers::getRequestParam('sid')) !== intval($jwtService->jwtObj->Payload['sid']->getValue())) {
            throw new CustomException('系统校验错误');
        }

        //设置登录账号
        \Yii::$app->user->identity = $jwtService->jwtObj->admin;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}